# Generated by Django 4.2.2 on 2023-09-04 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0003_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendingmachineslot',
            name='column',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
